server:
  port: 8181
spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/todotodo
    username: root
    password: mariadb
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
upload:
  path: D:/upload